name: First workflow
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
    - name: echo a string
      run: echo "Hello, world!"
    - name: Multline command
      run: |
        node -v
        npm -v

  parallel-job-macos:
    runs-on: macos-latest
    steps:
    - name: View SW version
      run: sw_vers
  dependent-job:
    needs: [run-shell-commands]
    runs-on: windows-latest
    steps:
    - name: echo a string
      run: Write-Output "Hello, world!"
    - name: Error Step
      run: doesnotexists